### ISSUE TITLE
[Backend]EloquentのScopeの呼び出しは、小文字始まり（ローワーキャメルケース）にしましょう

### ISSUE THREAD

**Issue by ynaka6** [tomo778/laravel_spa#2]
https://github.com/tomo778/laravel_spa/blob/d84c46dec8ecdfca142095db5d480732c534231b/app/Http/Controllers/NewsController.php#L23

https://github.com/tomo778/laravel_spa/blob/d84c46dec8ecdfca142095db5d480732c534231b/app/News.php#L40-L43

```
->statusCheck()
```

のような小文字始まりでいいかと思います。

**Comment by tomo778** [comment]
ありがとうございました。
対応しました。
