### ISSUE TITLE
[Backend]pluckを利用して１つのカラムのデータを取得する

### ISSUE THREAD

**Issue by ynaka6** [tomo778/laravel_spa#4]
以下のソースを見ていて、pluckを利用した方が効率的＆シンプルにソースがかけると思ったので、pluck を利用した実装方法を提案します。

https://github.com/tomo778/laravel_spa/blob/d84c46dec8ecdfca142095db5d480732c534231b/app/Http/Controllers/NewsController.php#L37-L47

```
 $ids = CategoryRel::where('category_id', $request->id)->pluck('news_id'); 
 $news = News::with('add_category') 
     ->StatusCheck() 
     ->whereIn('id', $ids) 
     ->orderBy('created_at', 'desc') 
     ->paginate(10); 
```

pluckを利用するとSELECT文のカラムが指定されたカラムのみになります。
また、今回は１つのカラムなので、news_idが入ったCollectionが取得されます。
news_idを配列に入れ直す必要がない為、ソースもシンプルになります。

**Comment by tomo778** [comment]
ありがとうございました。
対応しました。
Collectionについて詳しくなりたいと思います。
