### ISSUE TITLE
[Backend]DB::tableのクエリービルダーではなく、Eloquentモデルを利用する

### ISSUE THREAD

**Issue by ynaka6** [tomo778/laravel_spa#5]
Eloquentのモデルが定義されている場合、DB::tableを利用したクエリービルダー生成ではなくEloquentモデルからクエリービルダーを生成しましょう。

https://github.com/tomo778/laravel_spa/blob/d84c46dec8ecdfca142095db5d480732c534231b/app/Http/Controllers/Admin/CategoryController.php#L57

```
$q = Category::query();
```

で、クエリービルダーのインスタンスが生成されます。

### [メリット]
- ソースコードの統一（一部だけDB::tableを利用すると統一感がない為）
- Eloquentモデルからクエリービルダーを生成すると、取得したデータをEloquentモデルにバインドしてくれます（DB::tableの場合は連想配列）。モデルのfunctionを呼び出したい場合なども考慮するとEloquentモデルで取得する方がメリットがあります

**Comment by tomo778** [comment]
ありがとうございました。
対応しました。

この点はいい方法を探していたので、助かりました。
マニュアルをよく読まないといけないなーと感じました。
