### ISSUE TITLE
axiosとXSRF-TOKENについて

### ISSUE THREAD

**Issue by ynaka6** [tomo778/laravel_spa#7]
https://github.com/tomo778/laravel_spa/blob/d84c46dec8ecdfca142095db5d480732c534231b/resources/js/bootstrap.js#L8-L13

公式ドキュメントの以下の部分に記載がありますが、axiosではいつのバージョンからかわかってないんですが、自動でXSRF-TOKENをヘッダーに設定してくれるようになりました。

https://laravel.com/docs/7.x/csrf#csrf-x-xsrf-token
>  the Axios HTTP library provided in the resources/js/bootstrap.js file automatically sends an X-XSRF-TOKEN header using the value of the encrypted XSRF-TOKEN cookie. 

intercepterでheaderに設定しなくても機能すると思います。
（チュートリアルがそうなってたとは思いますが

**Comment by tomo778** [comment]
ありがとうございました。
対応しました。
