### ISSUE TITLE
[Frontend]ComponentからのVuexの方法について

### ISSUE THREAD

**Issue by ynaka6** [tomo778/laravel_spa#9]
### [概要]
Vuexで定義した関数・Stateについてですが、mapState, mapGetters, mapMutations, mapActionsを利用してページコンポーネント内にインポートすることで、処理をシンプルにすることが可能です。
ご検討ください。

主に`mapGetters` のState取得。`mapActions`のState更新を利用します。
gettersを介してStateを取得する為、`mapState`はほとんど使ったことない気がします。
また、ページコンポーネントから呼び出しは、action -> mutationで統一し、ページコンポーネント内で、action, mutationそれぞれ呼び出すことがないようにしましょう。

以下のフローを参考にしてください。
https://medium.com/vue-mastery/vuex-explained-visually-f17c8c76d6c4

![スクリーンショット 2020-06-02 午前6 13 53](https://user-images.githubusercontent.com/36042069/83460148-4c481c80-a498-11ea-94b9-3e6be467e9e6.png)

`mapGetters`はcomputedに、`mapActions`はmethodsにバインドできるので、ページコンポーネントに存在する変数、関数のように扱うことができます。

### [対象]
```
this.$store.getters["config/config"];
this.$store.commit("loadingBar/start");
```
https://github.com/tomo778/laravel_spa/blob/3cebfcbea40f9c16326c8d02b5dab9c576fd1ab5/resources/js/admin/pages/news/List.vue#L123

### [参考記事]
https://qiita.com/terufumi1122/items/6f9470c8d416a4af7502
https://vuex.vuejs.org/guide/actions.html#dispatching-actions-in-components

**Comment by tomo778** [comment]
作業しました。
確認お願い致します。

**Comment by ynaka6** [comment]
@tomo778 
修正有難うございます。問題ないかと思います。
